name: lein-test
run-name: lein test
on: [push]
jobs:
  lein-test:
    runs-on: ubuntu-latest
    container: clojure:temurin-11-lein-alpine
    steps:
      - uses: actions/checkout@v3
      - run: lein test
